# Generated by Django 5.2.8 on 2025-12-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_product_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cena",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cena",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dla_kogo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dla_niej", "Dla niej"),
                    ("dla_niego", "Dla niego"),
                    ("unisex", "Unisex"),
                ],
                max_length=20,
                verbose_name="Dla kogo",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dlugosc_kategoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("krotkie", "Krótkie"),
                    ("srednie", "Średnie"),
                    ("dlugie", "Długie"),
                    ("bardzo_dlugie", "Bardzo długie"),
                ],
                max_length=20,
                verbose_name="Długość kategoria",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dlugosc_w_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Długość w cm",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gatunek_ptakow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bazant", "Bażant"),
                    ("emu", "Emu"),
                    ("gawron", "Gawron"),
                    ("indyk", "Indyk"),
                    ("kura_kogut", "Kura lub kogut"),
                    ("papuga", "Papuga"),
                    ("paw", "Paw"),
                    ("perlica", "Perlica"),
                    ("inny", "Inny"),
                ],
                max_length=30,
                verbose_name="Pióra zgubiły (gatunek)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="kolor_elementow_metalowych",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zloty", "Złoty"),
                    ("srebrny", "Srebrny"),
                    ("mieszany", "Mieszany"),
                    ("inny", "Inny"),
                ],
                max_length=20,
                verbose_name="Kolor elementów metalowych",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="kolor_pior",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bezowy", "Beżowy"),
                    ("bialy", "Biały"),
                    ("brazowy", "Brązowy"),
                    ("czerwony", "Czerwony"),
                    ("czarny", "Czarny"),
                    ("granatowy", "Granatowy"),
                    ("niebieski", "Niebieski"),
                    ("rozowy", "Różowy"),
                    ("szary", "Szary"),
                    ("turkusowy", "Turkusowy"),
                    ("wzor", "Wzór"),
                    ("zolty", "Żółty"),
                    ("wielokolorowe", "Wielokolorowe"),
                ],
                max_length=30,
                verbose_name="Kolor piór w przewadze",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="nr_w_katalogu_zdjec",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nr w katalogu zdjęć"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="opis",
            field=models.TextField(blank=True, verbose_name="Opis"),
        ),
        migrations.AddField(
            model_name="product",
            name="przeznaczenie_ogolne",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kolczyki_para", "Do ucha - kolczyki (para)"),
                    ("kolczyki_asymetria", "Do ucha - kolczyki (asymetria)"),
                    ("kolczyki_single", "Do ucha - kolczyki (single)"),
                    ("kolczyki_komplet", "Do ucha - kolczyki (komplet z wisiorkiem)"),
                    ("zausznice", "Zausznice"),
                    ("na_szyje", "Na szyję"),
                    ("na_reke", "Na rękę"),
                    ("do_wlosow", "Do włosów"),
                    ("inne", "Inne"),
                ],
                max_length=50,
                verbose_name="Przeznaczenie ogólne",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pytanie_o_przedmiot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zamiana_zapiecia", "Zamiana zapięcia"),
                    ("inna_przerobka", "Inna przeróbka"),
                    ("szybsza_wysylka", "Szybsza wysyłka"),
                    ("zamowienie_indywidualne", "Zamówienie indywidualne"),
                    ("odbior_osobisty", "Odbiór osobisty"),
                    ("inne", "Inne"),
                ],
                max_length=50,
                verbose_name="Pytanie o przedmiot",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rodzaj_zapiecia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bigiel_otwarty", "Bigiel otwarty"),
                    ("bigiel_zamkniety", "Bigiel zamknięty"),
                    ("sztyft", "Sztyft"),
                    ("kolko", "Kółko"),
                    ("klips", "Klips"),
                    ("zausznik", "Zausznik"),
                    ("inny", "Inny"),
                    ("nie_dotyczy", "Nie dotyczy"),
                ],
                max_length=30,
                verbose_name="Rodzaj zapięcia",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tytul",
            field=models.CharField(blank=True, max_length=255, verbose_name="Tytuł"),
        ),
    ]
