# Generated by Django 5.2.8 on 2025-12-17 17:37

from django.db import migrations, models


def convert_char_to_json(apps, schema_editor):
    """Convert CharField values to JSON arrays"""
    Product = apps.get_model('home', 'Product')
    for product in Product.objects.all():
        # Convert dla_kogo
        if product.dla_kogo and product.dla_kogo.strip():
            product.dla_kogo = [product.dla_kogo]
        else:
            product.dla_kogo = []

        # Convert kolor_pior
        if product.kolor_pior and product.kolor_pior.strip():
            product.kolor_pior = [product.kolor_pior]
        else:
            product.kolor_pior = []

        # Convert gatunek_ptakow
        if product.gatunek_ptakow and product.gatunek_ptakow.strip():
            product.gatunek_ptakow = [product.gatunek_ptakow]
        else:
            product.gatunek_ptakow = []

        # Convert rodzaj_zapiecia
        if product.rodzaj_zapiecia and product.rodzaj_zapiecia.strip():
            product.rodzaj_zapiecia = [product.rodzaj_zapiecia]
        else:
            product.rodzaj_zapiecia = []

        product.save()


def reverse_json_to_char(apps, schema_editor):
    """Reverse: Convert JSON arrays back to CharField values"""
    Product = apps.get_model('home', 'Product')
    for product in Product.objects.all():
        # Convert dla_kogo
        if isinstance(product.dla_kogo, list) and product.dla_kogo:
            product.dla_kogo = product.dla_kogo[0]
        else:
            product.dla_kogo = ''

        # Convert kolor_pior
        if isinstance(product.kolor_pior, list) and product.kolor_pior:
            product.kolor_pior = product.kolor_pior[0]
        else:
            product.kolor_pior = ''

        # Convert gatunek_ptakow
        if isinstance(product.gatunek_ptakow, list) and product.gatunek_ptakow:
            product.gatunek_ptakow = product.gatunek_ptakow[0]
        else:
            product.gatunek_ptakow = ''

        # Convert rodzaj_zapiecia
        if isinstance(product.rodzaj_zapiecia, list) and product.rodzaj_zapiecia:
            product.rodzaj_zapiecia = product.rodzaj_zapiecia[0]
        else:
            product.rodzaj_zapiecia = ''

        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_product_cena_product_dla_kogo_and_more"),
    ]

    operations = [
        # First, convert existing data
        migrations.RunPython(convert_char_to_json, reverse_json_to_char),
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(
                default=True, verbose_name="Czy dostepny w sklepie"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cena",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cena promocyjna",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Opis (ang.)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="dla_kogo",
            field=models.JSONField(blank=True, default=list, verbose_name="Dla kogo"),
        ),
        migrations.AlterField(
            model_name="product",
            name="gatunek_ptakow",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Pióra zgubiły (gatunek)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="kolor_pior",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Kolor piór w przewadze"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nazwa (ang.)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="opis",
            field=models.TextField(blank=True, verbose_name="Opis (pl.)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Cena podstawowa"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="Automatycznie generowane z nazwy", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Automatycznie generowane przez Stripe",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Automatycznie generowane przez Stripe",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tytul",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nazwa (pl.)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rodzaj_zapiecia",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Rodzaj zapięcia"
            ),
        ),
    ]
