# Generated by Django 5.2.8 on 2025-12-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_product_dlugosc_kategoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="dlugosc_kategoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("krotkie", "Krótkie"),
                    ("srednie", "Średnie"),
                    ("dlugie", "Długie"),
                    ("bardzo_dlugie", "Bardzo długie"),
                ],
                default="",
                max_length=255,
                verbose_name="Długość kategoria",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="kolor_elementow_metalowych",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zloty", "Złoty"),
                    ("srebrny", "Srebrny"),
                    ("mieszany", "Mieszany"),
                    ("inny", "Inny"),
                ],
                default="",
                max_length=255,
                verbose_name="Kolor elementów metalowych",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="nr_w_katalogu_zdjec",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Nr w katalogu zdjęć",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="przeznaczenie_ogolne",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kolczyki_para", "Do ucha - kolczyki (para)"),
                    ("kolczyki_asymetria", "Do ucha - kolczyki (asymetria)"),
                    ("kolczyki_single", "Do ucha - kolczyki (single)"),
                    ("kolczyki_komplet", "Do ucha - kolczyki (komplet z wisiorkiem)"),
                    ("zausznice", "Zausznice"),
                    ("na_szyje", "Na szyję"),
                    ("na_reke", "Na rękę"),
                    ("do_wlosow", "Do włosów"),
                    ("inne", "Inne"),
                ],
                default="",
                max_length=255,
                verbose_name="Przeznaczenie ogólne",
            ),
        ),
    ]
