# Generated by Django 6.0 on 2026-01-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_product_description_alter_product_opis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Automatycznie generowane z nazwy",
                max_length=255,
                unique=True,
            ),
        ),
    ]
