# Generated by Django 6.0 on 2026-02-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="external_url",
            field=models.URLField(
                blank=True, verbose_name="Link do zewnętrznej strony wydarzenia"
            ),
        ),
    ]
