# Generated by Django 6.0 on 2026-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_product_dlugosc_kategoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data sprzedaży"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("sold", "Sold"),
                ],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "-created_at"], name="home_produc_status_3f98c4_idx"
            ),
        ),
    ]
